services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - "${API_PORT}:5000"
    volumes:
      - ./backend:/app

